name: newborn

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4        

      - name: Clean old commits
        run: |
            git config --global user.name "shilonit"
            git config --global user.email "shilonit@users.noreply.github.com"
            git checkout --orphan latest_branch
            git add -A
            git commit -am "New life"
            git branch -D main
            git branch -m main
            git push -f origin main
